// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, monthly_income)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, monthly_income, payment_day, currency, created_at`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.MonthlyIncome)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.MonthlyIncome, &i.PaymentDay, &i.Currency, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, monthly_income, payment_day, currency, created_at FROM users WHERE email = $1`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.MonthlyIncome, &i.PaymentDay, &i.Currency, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, monthly_income, payment_day, currency, created_at FROM users WHERE id = $1`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.MonthlyIncome, &i.PaymentDay, &i.Currency, &i.CreatedAt)
	return i, err
}

const updateUserIncome = `-- name: UpdateUserIncome :one
UPDATE users SET monthly_income = $2 WHERE id = $1 RETURNING id, email, password_hash, monthly_income, payment_day, currency, created_at`

func (q *Queries) UpdateUserIncome(ctx context.Context, id int64, monthlyIncome pgtype.Numeric) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIncome, id, monthlyIncome)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.MonthlyIncome, &i.PaymentDay, &i.Currency, &i.CreatedAt)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users SET monthly_income = $2, payment_day = $3, currency = $4 WHERE id = $1
RETURNING id, email, password_hash, monthly_income, payment_day, currency, created_at`

type UpdateUserSettingsParams struct {
	ID            int64
	MonthlyIncome pgtype.Numeric
	PaymentDay    *int32
	Currency      string
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.MonthlyIncome, arg.PaymentDay, arg.Currency)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.MonthlyIncome, &i.PaymentDay, &i.Currency, &i.CreatedAt)
	return i, err
}
